---
galaxy_info:
  author: IPvSean
  description: Issue Let's Encrypt SSL certificates for containerized Ansible Automation Platform with nginx reverse proxy
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - 8
        - 9

dependencies: []
